/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */

const iconActiveStyles = {
  default: { color: "x4hq6eo", $$css: true },
  error: { color: "xilsuq", $$css: true },
  info: { color: "x923533", $$css: true },
  inverted: { color: "x140t73q", $$css: true },
  marker: { color: "x1vvsez5", $$css: true },
  placeholder: { color: "x6lvj10", $$css: true },
  success: { color: "xdyirqe", $$css: true },
  warning: { color: "x746shc", $$css: true },
};

const iconDisabledStyles = {
  default: { color: "x150cnoy", $$css: true },
  error: { color: "x1n17xqh", $$css: true },
  info: { color: "x1yjqqfx", $$css: true },
  inverted: { color: "xto31z9", $$css: true },
  marker: { color: "x1vvsez5", $$css: true },
  placeholder: { color: "x9c3zl9", $$css: true },
  success: { color: "x2o0mob", $$css: true },
  warning: { color: "x10iwbtc", $$css: true },
};

const borderDefaultActiveStyles = {
  button: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  control: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  divider: {
    borderTopColor: "xxh5dwz",
    borderEndColor: "x1klwvkx",
    borderBottomColor: "x136yy5x",
    borderStartColor: "x14baxfg",
    $$css: true,
  },
  element: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  error: {
    borderTopColor: "x1f29zjl",
    borderEndColor: "x1fuj67e",
    borderBottomColor: "xpvhgef",
    borderStartColor: "xr9dbrz",
    $$css: true,
  },
  frame: {
    borderTopColor: "x1qyvd2d",
    borderEndColor: "x16cu5w9",
    borderBottomColor: "xoul6tu",
    borderStartColor: "x2qkk2",
    $$css: true,
  },
  info: {
    borderTopColor: "x1nzp1ka",
    borderEndColor: "x19bpa06",
    borderBottomColor: "x8uew1",
    borderStartColor: "x8e7i6l",
    $$css: true,
  },
  mainNavigationSelected: {
    borderTopColor: "xk3090t",
    borderEndColor: "xl7eqiy",
    borderBottomColor: "xmmdwdf",
    borderStartColor: "x1jopdh1",
    $$css: true,
  },
  success: {
    borderTopColor: "x1p3az52",
    borderEndColor: "xkfp8yk",
    borderBottomColor: "x1py6mlr",
    borderStartColor: "xkk4w0o",
    $$css: true,
  },
  warning: {
    borderTopColor: "x1yh48zd",
    borderEndColor: "x4vtfqn",
    borderBottomColor: "xia54jr",
    borderStartColor: "x1myal5o",
    $$css: true,
  },
};

const borderDefaultDisabledStyles = {
  button: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  control: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  divider: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  element: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  error: {
    borderTopColor: "x11odbn4",
    borderEndColor: "xah6pmm",
    borderBottomColor: "xfho9m3",
    borderStartColor: "xnhjz54",
    $$css: true,
  },
  frame: {
    borderTopColor: "x17br7ac",
    borderEndColor: "xez219c",
    borderBottomColor: "xo3d0r6",
    borderStartColor: "x1hd6qti",
    $$css: true,
  },
  info: {
    borderTopColor: "x1gmergp",
    borderEndColor: "x1s4se2m",
    borderBottomColor: "xt8hko0",
    borderStartColor: "x1bo3sr7",
    $$css: true,
  },
  mainNavigationSelected: {
    borderTopColor: "x1sqlwr6",
    borderEndColor: "xrc621n",
    borderBottomColor: "x1gcplko",
    borderStartColor: "x7ymq3u",
    $$css: true,
  },
  success: {
    borderTopColor: "x1ye665i",
    borderEndColor: "x1n3wcwz",
    borderBottomColor: "xzd4j2o",
    borderStartColor: "x19nl1lb",
    $$css: true,
  },
  warning: {
    borderTopColor: "xsckyur",
    borderEndColor: "xa64ehz",
    borderBottomColor: "x1jyvsjm",
    borderStartColor: "xyvv1sq",
    $$css: true,
  },
};

const borderFocusedActiveStyles = {
  button: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  control: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  divider: {
    borderTopColor: "xxh5dwz",
    borderEndColor: "x1klwvkx",
    borderBottomColor: "x136yy5x",
    borderStartColor: "x14baxfg",
    $$css: true,
  },
  element: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  error: {
    borderTopColor: "xlrknr9",
    borderEndColor: "x14e8xwt",
    borderBottomColor: "xa6b8qs",
    borderStartColor: "xrm4nz7",
    $$css: true,
  },
  frame: {
    borderTopColor: "x1qyvd2d",
    borderEndColor: "x16cu5w9",
    borderBottomColor: "xoul6tu",
    borderStartColor: "x2qkk2",
    $$css: true,
  },
  info: {
    borderTopColor: "x8avcdo",
    borderEndColor: "x1uuat95",
    borderBottomColor: "x1b4moik",
    borderStartColor: "x1tv5ldd",
    $$css: true,
  },
  mainNavigationSelected: {
    borderTopColor: "xk3090t",
    borderEndColor: "xl7eqiy",
    borderBottomColor: "xmmdwdf",
    borderStartColor: "x1jopdh1",
    $$css: true,
  },
  success: {
    borderTopColor: "x47k0b6",
    borderEndColor: "xev7war",
    borderBottomColor: "x8kuxpe",
    borderStartColor: "x306xey",
    $$css: true,
  },
  warning: {
    borderTopColor: "x1fr7rrh",
    borderEndColor: "x1we963t",
    borderBottomColor: "xoucf1v",
    borderStartColor: "x1yupf9g",
    $$css: true,
  },
};

const borderFocusedDisabledStyles = {
  button: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  control: {
    borderTopColor: "x1hwfl5k",
    borderEndColor: "xd1xcye",
    borderBottomColor: "x1vx98v3",
    borderStartColor: "x1eh26b4",
    $$css: true,
  },
  divider: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  element: {
    borderTopColor: "xb9moi8",
    borderEndColor: "xfth1om",
    borderBottomColor: "x21b0me",
    borderStartColor: "xmls85d",
    $$css: true,
  },
  error: {
    borderTopColor: "xnf1nyb",
    borderEndColor: "x9cq8o4",
    borderBottomColor: "xvieuqt",
    borderStartColor: "xk35g3i",
    $$css: true,
  },
  frame: {
    borderTopColor: "x17br7ac",
    borderEndColor: "xez219c",
    borderBottomColor: "xo3d0r6",
    borderStartColor: "x1hd6qti",
    $$css: true,
  },
  info: {
    borderTopColor: "x1jgf6j9",
    borderEndColor: "x1x1exb7",
    borderBottomColor: "x13mxa8r",
    borderStartColor: "xmdwe21",
    $$css: true,
  },
  mainNavigationSelected: {
    borderTopColor: "x1sqlwr6",
    borderEndColor: "xrc621n",
    borderBottomColor: "x1gcplko",
    borderStartColor: "x7ymq3u",
    $$css: true,
  },
  success: {
    borderTopColor: "xp9jigy",
    borderEndColor: "xqzltms",
    borderBottomColor: "xwdw8cy",
    borderStartColor: "xihadzq",
    $$css: true,
  },
  warning: {
    borderTopColor: "xxge7q2",
    borderEndColor: "x14h60gt",
    borderBottomColor: "x1eke3mv",
    borderStartColor: "x1f90l5c",
    $$css: true,
  },
};

const interactiveBorderDefaultActiveStyles = {
  button: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  control: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  divider: { outlineColor: "x18gw13d", outlineStyle: "xaatb59", $$css: true },
  element: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  error: { outlineColor: "x1rd70wb", outlineStyle: "xaatb59", $$css: true },
  frame: { outlineColor: "x47o8lo", outlineStyle: "xaatb59", $$css: true },
  info: { outlineColor: "x1jt2ctn", outlineStyle: "xaatb59", $$css: true },
  mainNavigationSelected: {
    outlineColor: "xe4nkwv",
    outlineStyle: "xaatb59",
    $$css: true,
  },
  success: { outlineColor: "xwt4hiq", outlineStyle: "xaatb59", $$css: true },
  warning: { outlineColor: "xvg9o4p", outlineStyle: "xaatb59", $$css: true },
};

const interactiveBorderDefaultDisabledStyles = {
  button: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  control: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  divider: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  element: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  error: { outlineColor: "x18nicxw", outlineStyle: "xaatb59", $$css: true },
  frame: { outlineColor: "xb2bza1", outlineStyle: "xaatb59", $$css: true },
  info: { outlineColor: "x1k7o0i0", outlineStyle: "xaatb59", $$css: true },
  mainNavigationSelected: {
    outlineColor: "xhgzu67",
    outlineStyle: "xaatb59",
    $$css: true,
  },
  success: { outlineColor: "xxj33bx", outlineStyle: "xaatb59", $$css: true },
  warning: { outlineColor: "xktpz7v", outlineStyle: "xaatb59", $$css: true },
};

const interactiveBorderFocusedActiveStyles = {
  button: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  control: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  divider: { outlineColor: "x18gw13d", outlineStyle: "xaatb59", $$css: true },
  element: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  error: { outlineColor: "x1ww3coq", outlineStyle: "xaatb59", $$css: true },
  frame: { outlineColor: "x47o8lo", outlineStyle: "xaatb59", $$css: true },
  info: { outlineColor: "xejlkim", outlineStyle: "xaatb59", $$css: true },
  mainNavigationSelected: {
    outlineColor: "xe4nkwv",
    outlineStyle: "xaatb59",
    $$css: true,
  },
  success: { outlineColor: "xqirkxh", outlineStyle: "xaatb59", $$css: true },
  warning: { outlineColor: "x1barh0j", outlineStyle: "xaatb59", $$css: true },
};

const interactiveBorderFocusedDisabledStyles = {
  button: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  control: { outlineColor: "xx6esqt", outlineStyle: "xaatb59", $$css: true },
  divider: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  element: { outlineColor: "x1mxyysi", outlineStyle: "xaatb59", $$css: true },
  error: { outlineColor: "xhae8h5", outlineStyle: "xaatb59", $$css: true },
  frame: { outlineColor: "xb2bza1", outlineStyle: "xaatb59", $$css: true },
  info: { outlineColor: "xc88c14", outlineStyle: "xaatb59", $$css: true },
  mainNavigationSelected: {
    outlineColor: "xhgzu67",
    outlineStyle: "xaatb59",
    $$css: true,
  },
  success: { outlineColor: "x1jzywy4", outlineStyle: "xaatb59", $$css: true },
  warning: { outlineColor: "xovt8d8", outlineStyle: "xaatb59", $$css: true },
};

const categoricalBackgroundIdleStyles = {
  0: { backgroundColor: "x15b7j53", $$css: true },
  1: { backgroundColor: "xx490rm", $$css: true },
  2: { backgroundColor: "x1vxgkma", $$css: true },
  3: { backgroundColor: "xev6e05", $$css: true },
  4: { backgroundColor: "x1okw7gl", $$css: true },
  5: { backgroundColor: "xm27y4y", $$css: true },
  6: { backgroundColor: "x1rcjd8h", $$css: true },
  7: { backgroundColor: "xj31fhn", $$css: true },
};

const categoricalForegroundTextStyles = {
  0: { color: "x1kq3dli", $$css: true },
  1: { color: "x3yajuq", $$css: true },
  2: { color: "x16ekl0a", $$css: true },
  3: { color: "x1ucbko1", $$css: true },
  4: { color: "x9ieef6", $$css: true },
  5: { color: "x3m00aj", $$css: true },
  6: { color: "x1pimas5", $$css: true },
  7: { color: "x1f2mhan", $$css: true },
};

const staticBackgroundStyles = {
  content: { backgroundColor: "x1gzqxud", $$css: true },
  error: { backgroundColor: "x1q6shm8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  inactive: { backgroundColor: "xas4zb2", $$css: true },
  info: { backgroundColor: "xb57al4", $$css: true },
  mainNavigationSelected: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xgyuhzn", $$css: true },
  overlay: { backgroundColor: "x1c8ul09", $$css: true },
  page: { backgroundColor: "xq4jnbd", $$css: true },
  selected: { backgroundColor: "xlvp1be", $$css: true },
  success: { backgroundColor: "x1bmepy4", $$css: true },
  warning: { backgroundColor: "x1adlnos", $$css: true },
  wash: { backgroundColor: "xas4zb2", $$css: true },
};

const staticBackgroundInvertedStyles = {
  content: { backgroundColor: "x1av4zun", $$css: true },
  error: { backgroundColor: "x1q6shm8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  inactive: { backgroundColor: "xas4zb2", $$css: true },
  info: { backgroundColor: "xb57al4", $$css: true },
  mainNavigationSelected: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xgyuhzn", $$css: true },
  overlay: { backgroundColor: "x1c8ul09", $$css: true },
  page: { backgroundColor: "xq4jnbd", $$css: true },
  selected: { backgroundColor: "xlvp1be", $$css: true },
  success: { backgroundColor: "x1bmepy4", $$css: true },
  warning: { backgroundColor: "x1adlnos", $$css: true },
  wash: { backgroundColor: "x1ybmbna", $$css: true },
};

const staticBackgroundMutedStyles = {
  content: { backgroundColor: "x1gzqxud", $$css: true },
  error: { backgroundColor: "x1952bq8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  inactive: { backgroundColor: "xas4zb2", $$css: true },
  info: { backgroundColor: "xlvp1be", $$css: true },
  mainNavigationSelected: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xgyuhzn", $$css: true },
  overlay: { backgroundColor: "x1c8ul09", $$css: true },
  page: { backgroundColor: "xq4jnbd", $$css: true },
  selected: { backgroundColor: "xlvp1be", $$css: true },
  success: { backgroundColor: "x1fwvgxd", $$css: true },
  warning: { backgroundColor: "xduklol", $$css: true },
  wash: { backgroundColor: "x1yhoyej", $$css: true },
};

const staticBackgroundInvertedMutedStyles = {
  content: { backgroundColor: "x1av4zun", $$css: true },
  error: { backgroundColor: "x1q6shm8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  inactive: { backgroundColor: "xas4zb2", $$css: true },
  info: { backgroundColor: "xb57al4", $$css: true },
  mainNavigationSelected: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xgyuhzn", $$css: true },
  overlay: { backgroundColor: "x1c8ul09", $$css: true },
  page: { backgroundColor: "xq4jnbd", $$css: true },
  selected: { backgroundColor: "xlvp1be", $$css: true },
  success: { backgroundColor: "x1bmepy4", $$css: true },
  warning: { backgroundColor: "x1adlnos", $$css: true },
  wash: { backgroundColor: "x1ybmbna", $$css: true },
};

const textActiveStyles = {
  error: { color: "x1ejwfya", $$css: true },
  heading: { color: "x4hq6eo", $$css: true },
  headingDescription: { color: "x4hq6eo", $$css: true },
  info: { color: "xwpu04d", $$css: true },
  link: { color: "xjnfcd9", $$css: true },
  placeholder: { color: "x6lvj10", $$css: true },
  success: { color: "x1fp01tm", $$css: true },
  value: { color: "x108nfp6", $$css: true },
  valueDescription: { color: "x4hq6eo", $$css: true },
  warning: { color: "xx3ys0k", $$css: true },
};

const textDisabledStyles = {
  error: { color: "x1gark0l", $$css: true },
  heading: { color: "x150cnoy", $$css: true },
  headingDescription: { color: "x150cnoy", $$css: true },
  info: { color: "x3rod1v", $$css: true },
  link: { color: "x931pkn", $$css: true },
  placeholder: { color: "x9c3zl9", $$css: true },
  success: { color: "xl8mqd3", $$css: true },
  value: { color: "x1kdmppe", $$css: true },
  valueDescription: { color: "x150cnoy", $$css: true },
  warning: { color: "xixgoho", $$css: true },
};

const textInvertedActiveStyles = {
  error: { color: "x1ejwfya", $$css: true },
  heading: { color: "x99e291", $$css: true },
  headingDescription: { color: "x99e291", $$css: true },
  info: { color: "xwpu04d", $$css: true },
  link: { color: "xjnfcd9", $$css: true },
  placeholder: { color: "xfiw4rn", $$css: true },
  success: { color: "x1fp01tm", $$css: true },
  value: { color: "x140t73q", $$css: true },
  valueDescription: { color: "x99e291", $$css: true },
  warning: { color: "xx3ys0k", $$css: true },
};

const textInvertedDisabledStyles = {
  error: { color: "x1gark0l", $$css: true },
  heading: { color: "xsokbok", $$css: true },
  headingDescription: { color: "xsokbok", $$css: true },
  info: { color: "x3rod1v", $$css: true },
  link: { color: "x931pkn", $$css: true },
  placeholder: { color: "x1t8b4hb", $$css: true },
  success: { color: "xl8mqd3", $$css: true },
  value: { color: "xto31z9", $$css: true },
  valueDescription: { color: "xsokbok", $$css: true },
  warning: { color: "xixgoho", $$css: true },
};

const interactiveBackgroundIdleStyles = {
  button: { backgroundColor: "xas4zb2", $$css: true },
  creation: { backgroundColor: "x1bmepy4", $$css: true },
  error: { backgroundColor: "x1952bq8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  flatInverted: { backgroundColor: "x8b1hf0", $$css: true },
  flatNavigation: { backgroundColor: "xlvp1be", $$css: true },
  input: { backgroundColor: "x1gzqxud", $$css: true },
  link: { backgroundColor: "x1v911su", $$css: true },
  mainNavigation: { backgroundColor: "x1v911su", $$css: true },
  mainNavigationSelected: { backgroundColor: "x1v911su", $$css: true },
  navigation: { backgroundColor: "xlvp1be", $$css: true },
  on: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xgyuhzn", $$css: true },
  primary: { backgroundColor: "xb57al4", $$css: true },
  selected: { backgroundColor: "xlvp1be", $$css: true },
  warning: { backgroundColor: "xduklol", $$css: true },
  wash: { backgroundColor: "xas4zb2", $$css: true },
};

const interactiveBackgroundActiveStyles = {
  button: { backgroundColor: "x1e4gqcv", $$css: true },
  creation: { backgroundColor: "xnc3ajd", $$css: true },
  error: { backgroundColor: "x1q5x5ga", $$css: true },
  flat: { backgroundColor: "x1si8nl4", $$css: true },
  flatInverted: { backgroundColor: "x1ohetei", $$css: true },
  flatNavigation: { backgroundColor: "xjtiqty", $$css: true },
  input: { backgroundColor: "xrh1vfq", $$css: true },
  link: { backgroundColor: "x1si8nl4", $$css: true },
  mainNavigation: { backgroundColor: "x1si8nl4", $$css: true },
  mainNavigationSelected: { backgroundColor: "x1si8nl4", $$css: true },
  navigation: { backgroundColor: "xjtiqty", $$css: true },
  on: { backgroundColor: "xb57al4", $$css: true },
  onboarding: { backgroundColor: "xj1bup", $$css: true },
  primary: { backgroundColor: "x1w7whrn", $$css: true },
  selected: { backgroundColor: "xjtiqty", $$css: true },
  warning: { backgroundColor: "xnamc57", $$css: true },
  wash: { backgroundColor: "x1e4gqcv", $$css: true },
};

const interactiveBackgroundDisabledStyles = {
  button: { backgroundColor: "x1si8nl4", $$css: true },
  creation: { backgroundColor: "xypzpgp", $$css: true },
  error: { backgroundColor: "x3n49o8", $$css: true },
  flat: { backgroundColor: "x1v911su", $$css: true },
  flatInverted: { backgroundColor: "x8b1hf0", $$css: true },
  flatNavigation: { backgroundColor: "xas4zb2", $$css: true },
  input: { backgroundColor: "xq4jnbd", $$css: true },
  link: { backgroundColor: "x1v911su", $$css: true },
  mainNavigation: { backgroundColor: "x1v911su", $$css: true },
  mainNavigationSelected: { backgroundColor: "x1v911su", $$css: true },
  navigation: { backgroundColor: "xas4zb2", $$css: true },
  on: { backgroundColor: "x1bbbera", $$css: true },
  onboarding: { backgroundColor: "x1tnfm5v", $$css: true },
  primary: { backgroundColor: "x16qzbjk", $$css: true },
  selected: { backgroundColor: "xas4zb2", $$css: true },
  warning: { backgroundColor: "xvfcu65", $$css: true },
  wash: { backgroundColor: "x1si8nl4", $$css: true },
};

const interactiveBackgroundFocusedStyles = {
  button: { backgroundColor: "x1si8nl4", $$css: true },
  creation: { backgroundColor: "xouchr0", $$css: true },
  error: { backgroundColor: "x1ui0n4m", $$css: true },
  flat: { backgroundColor: "xas4zb2", $$css: true },
  flatInverted: { backgroundColor: "xpj9qch", $$css: true },
  flatNavigation: { backgroundColor: "xb9hb0d", $$css: true },
  input: { backgroundColor: "x1c4k4jh", $$css: true },
  link: { backgroundColor: "xas4zb2", $$css: true },
  mainNavigation: { backgroundColor: "xas4zb2", $$css: true },
  mainNavigationSelected: { backgroundColor: "xas4zb2", $$css: true },
  navigation: { backgroundColor: "xb9hb0d", $$css: true },
  on: { backgroundColor: "x1natfvz", $$css: true },
  onboarding: { backgroundColor: "xa74hv5", $$css: true },
  primary: { backgroundColor: "x1natfvz", $$css: true },
  selected: { backgroundColor: "xb9hb0d", $$css: true },
  warning: { backgroundColor: "x1ub4f6", $$css: true },
  wash: { backgroundColor: "x1si8nl4", $$css: true },
};

const interactiveBackgroundTextWeightStyles = {
  button: { fontWeight: "xo1l8bm", $$css: true },
  creation: { fontWeight: "x1xlr1w8", $$css: true },
  error: { fontWeight: "xo1l8bm", $$css: true },
  flat: { fontWeight: "xo1l8bm", $$css: true },
  flatInverted: { fontWeight: "x1xlr1w8", $$css: true },
  flatNavigation: { fontWeight: "x1xlr1w8", $$css: true },
  input: { fontWeight: "xo1l8bm", $$css: true },
  link: { fontWeight: "xo1l8bm", $$css: true },
  mainNavigation: { fontWeight: "xo1l8bm", $$css: true },
  mainNavigationSelected: { fontWeight: "xo1l8bm", $$css: true },
  navigation: { fontWeight: "x1xlr1w8", $$css: true },
  on: { fontWeight: "x1xlr1w8", $$css: true },
  onboarding: { fontWeight: "xo1l8bm", $$css: true },
  primary: { fontWeight: "x1xlr1w8", $$css: true },
  selected: { fontWeight: "xo1l8bm", $$css: true },
  warning: { fontWeight: "xo1l8bm", $$css: true },
  wash: { fontWeight: "xo1l8bm", $$css: true },
};

const interactiveBackgroundTextActiveStyles = {
  button: { color: "x108nfp6", $$css: true },
  creation: { color: "x140t73q", $$css: true },
  error: { color: "x108nfp6", $$css: true },
  flat: { color: "x108nfp6", $$css: true },
  flatInverted: { color: "x140t73q", $$css: true },
  flatNavigation: { color: "xwpu04d", $$css: true },
  input: { color: "x108nfp6", $$css: true },
  link: { color: "xwpu04d", $$css: true },
  mainNavigation: { color: "x108nfp6", $$css: true },
  mainNavigationSelected: { color: "xwpu04d", $$css: true },
  navigation: { color: "xwpu04d", $$css: true },
  on: { color: "x140t73q", $$css: true },
  onboarding: { color: "x140t73q", $$css: true },
  primary: { color: "x140t73q", $$css: true },
  selected: { color: "x108nfp6", $$css: true },
  warning: { color: "x108nfp6", $$css: true },
  wash: { color: "x108nfp6", $$css: true },
};

const interactiveBackgroundTextDisabledStyles = {
  button: { color: "x1kdmppe", $$css: true },
  creation: { color: "xto31z9", $$css: true },
  error: { color: "x1gark0l", $$css: true },
  flat: { color: "x1kdmppe", $$css: true },
  flatInverted: { color: "xto31z9", $$css: true },
  flatNavigation: { color: "x3rod1v", $$css: true },
  input: { color: "x1kdmppe", $$css: true },
  link: { color: "x3rod1v", $$css: true },
  mainNavigation: { color: "x1kdmppe", $$css: true },
  mainNavigationSelected: { color: "x3rod1v", $$css: true },
  navigation: { color: "x3rod1v", $$css: true },
  on: { color: "xto31z9", $$css: true },
  onboarding: { color: "xto31z9", $$css: true },
  primary: { color: "xto31z9", $$css: true },
  selected: { color: "x1kdmppe", $$css: true },
  warning: { color: "xixgoho", $$css: true },
  wash: { color: "x1kdmppe", $$css: true },
};

const interactiveOverlayColorStyles = {
  button: { backgroundColor: "x12s6r1p", $$css: true },
  creation: { backgroundColor: "x12s6r1p", $$css: true },
  error: { backgroundColor: "x12s6r1p", $$css: true },
  flat: { backgroundColor: "x12s6r1p", $$css: true },
  flatInverted: { backgroundColor: "x1gzqxud", $$css: true },
  flatNavigation: { backgroundColor: "xb57al4", $$css: true },
  input: { backgroundColor: "x1gzqxud", $$css: true },
  link: { backgroundColor: "x12s6r1p", $$css: true },
  mainNavigation: { backgroundColor: "x12s6r1p", $$css: true },
  mainNavigationSelected: { backgroundColor: "x12s6r1p", $$css: true },
  navigation: { backgroundColor: "xb57al4", $$css: true },
  on: { backgroundColor: "x12s6r1p", $$css: true },
  onboarding: { backgroundColor: "x12s6r1p", $$css: true },
  primary: { backgroundColor: "x12s6r1p", $$css: true },
  selected: { backgroundColor: "xb57al4", $$css: true },
  warning: { backgroundColor: "x12s6r1p", $$css: true },
  wash: { backgroundColor: "x12s6r1p", $$css: true },
};

const interactiveOverlayIdleStyles = {
  button: { opacity: "xg01cxk", $$css: true },
  creation: { opacity: "xg01cxk", $$css: true },
  error: { opacity: "xg01cxk", $$css: true },
  flat: { opacity: "xg01cxk", $$css: true },
  flatInverted: { opacity: "xg01cxk", $$css: true },
  flatNavigation: { opacity: "xg01cxk", $$css: true },
  input: { opacity: "xg01cxk", $$css: true },
  link: { opacity: "xg01cxk", $$css: true },
  mainNavigation: { opacity: "xg01cxk", $$css: true },
  mainNavigationSelected: { opacity: "xg01cxk", $$css: true },
  navigation: { opacity: "xg01cxk", $$css: true },
  on: { opacity: "xg01cxk", $$css: true },
  onboarding: { opacity: "xg01cxk", $$css: true },
  primary: { opacity: "xg01cxk", $$css: true },
  selected: { opacity: "xg01cxk", $$css: true },
  warning: { opacity: "xg01cxk", $$css: true },
  wash: { opacity: "xg01cxk", $$css: true },
};

const interactiveOverlayFocusedStyles = {
  button: { opacity: "x1ptxcow", $$css: true },
  creation: { opacity: "x1ptxcow", $$css: true },
  error: { opacity: "x1ptxcow", $$css: true },
  flat: { opacity: "x1ptxcow", $$css: true },
  flatInverted: { opacity: "x1ptxcow", $$css: true },
  flatNavigation: { opacity: "x1xyvc85", $$css: true },
  input: { opacity: "x1ptxcow", $$css: true },
  link: { opacity: "x1ptxcow", $$css: true },
  mainNavigation: { opacity: "x1ptxcow", $$css: true },
  mainNavigationSelected: { opacity: "x1ptxcow", $$css: true },
  navigation: { opacity: "x1xyvc85", $$css: true },
  on: { opacity: "x1ptxcow", $$css: true },
  onboarding: { opacity: "x1ptxcow", $$css: true },
  primary: { opacity: "x1ptxcow", $$css: true },
  selected: { opacity: "x1xyvc85", $$css: true },
  warning: { opacity: "x1ptxcow", $$css: true },
  wash: { opacity: "x1ptxcow", $$css: true },
};

const interactiveOverlayActiveStyles = {
  button: { opacity: "x1xyvc85", $$css: true },
  creation: { opacity: "xz5rk10", $$css: true },
  error: { opacity: "x1xyvc85", $$css: true },
  flat: { opacity: "x1xyvc85", $$css: true },
  flatInverted: { opacity: "x1xyvc85", $$css: true },
  flatNavigation: { opacity: "xvpkmg4", $$css: true },
  input: { opacity: "x1xyvc85", $$css: true },
  link: { opacity: "x1xyvc85", $$css: true },
  mainNavigation: { opacity: "x1xyvc85", $$css: true },
  mainNavigationSelected: { opacity: "x1xyvc85", $$css: true },
  navigation: { opacity: "xvpkmg4", $$css: true },
  on: { opacity: "xz5rk10", $$css: true },
  onboarding: { opacity: "xz5rk10", $$css: true },
  primary: { opacity: "xz5rk10", $$css: true },
  selected: { opacity: "xvpkmg4", $$css: true },
  warning: { opacity: "x1xyvc85", $$css: true },
  wash: { opacity: "x1xyvc85", $$css: true },
};

const glimmerStyles = {
  0: {
    animationDelay: "x1uzojwf",
    animationName: "xrtjlq3",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
  1: {
    animationDelay: "x1t83zlg",
    animationName: "xrtjlq3",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
  2: {
    animationDelay: "x1xwhvez",
    animationName: "xrtjlq3",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
  3: {
    animationDelay: "x1nrwgbl",
    animationName: "x1camesu",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
  4: {
    animationDelay: "x1vvzlz1",
    animationName: "x1wfwbum",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
};

const glimmerVariantsStyles = {
  input: {
    animationName: "x5uexz0",
    backgroundColor: "xc1r0np",
    opacity: "xkk3ads",
    $$css: true,
  },
};

const barElementStrokeStyles = {
  light: { stroke: "x1606d9y", $$css: true },
  dark: { stroke: "x4mwgaj", $$css: true },
};

const trackElementStrokeStyles = {
  light: { stroke: "x1tnjt92", $$css: true },
  dark: { stroke: "x18z1ann", $$css: true },
};

const outlineActiveStyles = {
  button: { boxShadow: "x15u2huf", $$css: true },
  creation: { boxShadow: "x6zghsr", $$css: true },
  error: { boxShadow: "xo6rvx7", $$css: true },
  flat: { boxShadow: "x1d0qdvz", $$css: true },
  flatInverted: { boxShadow: "xbmzmm3", $$css: true },
  flatNavigation: { boxShadow: "x17ihpsl", $$css: true },
  input: { boxShadow: "xwwk14r", $$css: true },
  link: { boxShadow: "x1d0qdvz", $$css: true },
  mainNavigation: { boxShadow: "x1d0qdvz", $$css: true },
  mainNavigationSelected: { boxShadow: "x1d0qdvz", $$css: true },
  navigation: { boxShadow: "x17ihpsl", $$css: true },
  on: { boxShadow: "x1464af", $$css: true },
  onboarding: { boxShadow: "x3w23vw", $$css: true },
  primary: { boxShadow: "x8tw7v1", $$css: true },
  selected: { boxShadow: "x17ihpsl", $$css: true },
  warning: { boxShadow: "x5d84an", $$css: true },
  wash: { boxShadow: "x15u2huf", $$css: true },
};

const outlineFocusedStyles = {
  button: { boxShadow: "x1d0qdvz", $$css: true },
  creation: { boxShadow: "xk8u0jf", $$css: true },
  error: { boxShadow: "xt4f6be", $$css: true },
  flat: { boxShadow: "xq6q66p", $$css: true },
  flatInverted: { boxShadow: "x1hcs357", $$css: true },
  flatNavigation: { boxShadow: "x1rr46mp", $$css: true },
  input: { boxShadow: "xnwyait", $$css: true },
  link: { boxShadow: "xq6q66p", $$css: true },
  mainNavigation: { boxShadow: "xq6q66p", $$css: true },
  mainNavigationSelected: { boxShadow: "xq6q66p", $$css: true },
  navigation: { boxShadow: "x1rr46mp", $$css: true },
  on: { boxShadow: "x1t5zvq3", $$css: true },
  onboarding: { boxShadow: "x15f6gkv", $$css: true },
  primary: { boxShadow: "x1t5zvq3", $$css: true },
  selected: { boxShadow: "x1rr46mp", $$css: true },
  warning: { boxShadow: "x3vxpbe", $$css: true },
  wash: { boxShadow: "x1d0qdvz", $$css: true },
};

const onboardingTourHighlightStyles = {
  base: { boxShadow: "x1k3v63p", $$css: true },
};

const onboardingPulseAnimationStyles = {
  base: {
    animationName: "xnp97gk",
    animationIterationCount: "xa4qsjk",
    animationDuration: "x1c74tu6",
    $$css: true,
  },
};

export {
  barElementStrokeStyles,
  borderDefaultActiveStyles,
  borderDefaultDisabledStyles,
  borderFocusedActiveStyles,
  borderFocusedDisabledStyles,
  categoricalBackgroundIdleStyles,
  categoricalForegroundTextStyles,
  glimmerStyles,
  glimmerVariantsStyles,
  iconActiveStyles,
  iconDisabledStyles,
  interactiveBackgroundActiveStyles,
  interactiveBackgroundDisabledStyles,
  interactiveBackgroundFocusedStyles,
  interactiveBackgroundIdleStyles,
  interactiveBackgroundTextActiveStyles,
  interactiveBackgroundTextDisabledStyles,
  interactiveBackgroundTextWeightStyles,
  interactiveBorderDefaultActiveStyles,
  interactiveBorderDefaultDisabledStyles,
  interactiveBorderFocusedActiveStyles,
  interactiveBorderFocusedDisabledStyles,
  interactiveOverlayActiveStyles,
  interactiveOverlayColorStyles,
  interactiveOverlayFocusedStyles,
  interactiveOverlayIdleStyles,
  onboardingPulseAnimationStyles,
  onboardingTourHighlightStyles,
  outlineActiveStyles,
  outlineFocusedStyles,
  staticBackgroundInvertedMutedStyles,
  staticBackgroundInvertedStyles,
  staticBackgroundMutedStyles,
  staticBackgroundStyles,
  textActiveStyles,
  textDisabledStyles,
  textInvertedActiveStyles,
  textInvertedDisabledStyles,
  trackElementStrokeStyles,
};
