/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */

export const GeoPrivateDefaultSpacingGeneratedStyles = {
  containerInternalPageSpacingStyles: {
    bottom: { paddingBottom: "xwxc41k", $$css: true },
    top: { paddingTop: "x1p5oq8j", $$css: true },
    end: {
      paddingEnd: "xxbr6pl",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "xbbxn1n",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "xbbxn1n",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "xxbr6pl",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1p5oq8j",
      paddingBottom: "xwxc41k",
      $$css: true,
    },
  },
  containerInternalComponentSpacingStyles: {
    bottom: { paddingBottom: "x1l90r2v", $$css: true },
    top: { paddingTop: "xyamay9", $$css: true },
    end: {
      paddingEnd: "x1pi30zi",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "x1swvt13",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "x1swvt13",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x1pi30zi",
      $$css: true,
    },
    vertical: {
      paddingTop: "xyamay9",
      paddingBottom: "x1l90r2v",
      $$css: true,
    },
  },
  componentFineSpacingStyles: {
    bottom: { paddingBottom: "xjkvuk6", $$css: true },
    top: { paddingTop: "x1iorvi4", $$css: true },
    end: {
      paddingEnd: "x150jy0e",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "x1e558r4",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "x1e558r4",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x150jy0e",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1iorvi4",
      paddingBottom: "xjkvuk6",
      $$css: true,
    },
  },
  componentFineSpacingOffsetStyles: {
    bottom: { marginBottom: "x4vbgl9", $$css: true },
    top: { marginTop: "x1rdy4ex", $$css: true },
    end: {
      marginEnd: "xcud41i",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x139jcc6",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x139jcc6",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xcud41i",
      $$css: true,
    },
    vertical: {
      marginTop: "x1rdy4ex",
      marginBottom: "x4vbgl9",
      $$css: true,
    },
  },
  componentNormalSpacingStyles: {
    bottom: { paddingBottom: "xwib8y2", $$css: true },
    top: { paddingTop: "x1y1aw1k", $$css: true },
    end: {
      paddingEnd: "x1sxyh0",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "xurb0ha",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "xurb0ha",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x1sxyh0",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1y1aw1k",
      paddingBottom: "xwib8y2",
      $$css: true,
    },
  },
  componentNormalSpacingOffsetStyles: {
    bottom: { marginBottom: "x1wsgfga", $$css: true },
    top: { marginTop: "x9otpla", $$css: true },
    end: {
      marginEnd: "x1n0m28w",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "xp7jhwk",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "xp7jhwk",
      marginLeft: null,
      marginRight: null,
      marginEnd: "x1n0m28w",
      $$css: true,
    },
    vertical: {
      marginTop: "x9otpla",
      marginBottom: "x1wsgfga",
      $$css: true,
    },
  },
  componentCoarseSpacingStyles: {
    bottom: { paddingBottom: "xsag5q8", $$css: true },
    top: { paddingTop: "xz9dl7a", $$css: true },
    end: {
      paddingEnd: "xn6708d",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "x1ye3gou",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "x1ye3gou",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "xn6708d",
      $$css: true,
    },
    vertical: {
      paddingTop: "xz9dl7a",
      paddingBottom: "xsag5q8",
      $$css: true,
    },
  },
  componentCoarseSpacingOffsetStyles: {
    bottom: { marginBottom: "xh3wvx0", $$css: true },
    top: { marginTop: "x7wgvq7", $$css: true },
    end: {
      marginEnd: "x12rz0ws",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x16hk5td",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x16hk5td",
      marginLeft: null,
      marginRight: null,
      marginEnd: "x12rz0ws",
      $$css: true,
    },
    vertical: {
      marginTop: "x7wgvq7",
      marginBottom: "xh3wvx0",
      $$css: true,
    },
  },
  controlNormalSpacingStyles: {
    bottom: { paddingBottom: "xwib8y2", $$css: true },
    top: { paddingTop: "x1y1aw1k", $$css: true },
    end: {
      paddingEnd: "xn6708d",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "x1ye3gou",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "x1ye3gou",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "xn6708d",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1y1aw1k",
      paddingBottom: "xwib8y2",
      $$css: true,
    },
  },
  controlFineSpacingStyles: {
    bottom: { paddingBottom: "xwib8y2", $$css: true },
    top: { paddingTop: "x1y1aw1k", $$css: true },
    end: {
      paddingEnd: "x1sxyh0",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "xurb0ha",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "xurb0ha",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x1sxyh0",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1y1aw1k",
      paddingBottom: "xwib8y2",
      $$css: true,
    },
  },
  controlCoarseSpacingStyles: {
    bottom: { paddingBottom: "xwib8y2", $$css: true },
    top: { paddingTop: "x1y1aw1k", $$css: true },
    end: {
      paddingEnd: "x1pi30zi",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "x1swvt13",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "x1swvt13",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x1pi30zi",
      $$css: true,
    },
    vertical: {
      paddingTop: "x1y1aw1k",
      paddingBottom: "xwib8y2",
      $$css: true,
    },
  },
  inputSpacingStyles: {
    bottom: { paddingBottom: "x1ykpatu", $$css: true },
    top: { paddingTop: "xm7lytj", $$css: true },
    end: {
      paddingEnd: "x1w2lkzu",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    start: {
      paddingStart: "xlu9dua",
      paddingLeft: null,
      paddingRight: null,
      $$css: true,
    },
    horizontal: {
      paddingStart: "xlu9dua",
      paddingLeft: null,
      paddingRight: null,
      paddingEnd: "x1w2lkzu",
      $$css: true,
    },
    vertical: {
      paddingTop: "xm7lytj",
      paddingBottom: "x1ykpatu",
      $$css: true,
    },
  },
  containerExternalRelatedSpacingStyles: {
    bottom: { marginBottom: "x1e56ztr", $$css: true },
    top: { marginTop: "x1xmf6yo", $$css: true },
    end: {
      marginEnd: "x1emribx",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x1i64zmx",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x1i64zmx",
      marginLeft: null,
      marginRight: null,
      marginEnd: "x1emribx",
      $$css: true,
    },
    vertical: {
      marginTop: "x1xmf6yo",
      marginBottom: "x1e56ztr",
      $$css: true,
    },
  },
  layoutContainerExternalRelatedSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x19lwn94",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "x1cjjmgv",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "x1k3wvip",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x98vc6m",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
      ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
      $$css: true,
    },
  },
  containerExternalUnrelatedSpacingStyles: {
    bottom: { marginBottom: "x1yztbdb", $$css: true },
    top: { marginTop: "xw7yly9", $$css: true },
    end: {
      marginEnd: "xktsk01",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x1d52u69",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x1d52u69",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xktsk01",
      $$css: true,
    },
    vertical: {
      marginTop: "xw7yly9",
      marginBottom: "x1yztbdb",
      $$css: true,
    },
  },
  layoutContainerExternalUnrelatedSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x1jjk293",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "xg3tqtt",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "xe9zolg",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x1ywc1mj",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
      ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
      $$css: true,
    },
  },
  containerExternalSectionSpacingStyles: {
    bottom: { marginBottom: "x1iymm2a", $$css: true },
    top: { marginTop: "xg87l8a", $$css: true },
    end: {
      marginEnd: "x1gja9t",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x8vdgqj",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x8vdgqj",
      marginLeft: null,
      marginRight: null,
      marginEnd: "x1gja9t",
      $$css: true,
    },
    vertical: {
      marginTop: "xg87l8a",
      marginBottom: "x1iymm2a",
      $$css: true,
    },
  },
  layoutContainerExternalSectionSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x33y71p",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "x1w65fby",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "xy9qb40",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "x15topv2",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "x1iugkjb",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x9capae",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "x1w65fby",
      ":not([stylex-hack]) > * + *_marginBottom": "x33y71p",
      $$css: true,
    },
  },
  componentExternalRelatedSpacingStyles: {
    bottom: { marginBottom: "x12nagc", $$css: true },
    top: { marginTop: "x1gslohp", $$css: true },
    end: {
      marginEnd: "xw3qccf",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "xsgj6o6",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "xsgj6o6",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xw3qccf",
      $$css: true,
    },
    vertical: {
      marginTop: "x1gslohp",
      marginBottom: "x12nagc",
      $$css: true,
    },
  },
  layoutComponentExternalRelatedSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x65s2av",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "xsvltjl",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "xi9rg8n",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x1nvpu9x",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
      ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
      $$css: true,
    },
  },
  componentExternalUnrelatedSpacingStyles: {
    bottom: { marginBottom: "x1e56ztr", $$css: true },
    top: { marginTop: "x1xmf6yo", $$css: true },
    end: {
      marginEnd: "x1emribx",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x1i64zmx",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x1i64zmx",
      marginLeft: null,
      marginRight: null,
      marginEnd: "x1emribx",
      $$css: true,
    },
    vertical: {
      marginTop: "x1xmf6yo",
      marginBottom: "x1e56ztr",
      $$css: true,
    },
  },
  layoutComponentExternalUnrelatedSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x19lwn94",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "x1cjjmgv",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "x1k3wvip",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x98vc6m",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "xavht8x",
      ":not([stylex-hack]) > * + *_marginBottom": "x1n14ejq",
      $$css: true,
    },
  },
  contentExternalHeadingSpacingStyles: {
    bottom: { marginBottom: "x12nagc", $$css: true },
    top: { marginTop: "x1gslohp", $$css: true },
    end: {
      marginEnd: "xw3qccf",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "xsgj6o6",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "xsgj6o6",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xw3qccf",
      $$css: true,
    },
    vertical: {
      marginTop: "x1gslohp",
      marginBottom: "x12nagc",
      $$css: true,
    },
  },
  layoutContentExternalHeadingSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x65s2av",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "xsvltjl",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "xi9rg8n",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x1nvpu9x",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "xyqj3jm",
      ":not([stylex-hack]) > * + *_marginBottom": "x1xcg3fx",
      $$css: true,
    },
  },
  contentExternalParagraphSpacingStyles: {
    bottom: { marginBottom: "xod5an3", $$css: true },
    top: { marginTop: "x14vqqas", $$css: true },
    end: {
      marginEnd: "xq8finb",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x16n37ib",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x16n37ib",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xq8finb",
      $$css: true,
    },
    vertical: {
      marginTop: "x14vqqas",
      marginBottom: "xod5an3",
      $$css: true,
    },
  },
  layoutContentExternalParagraphSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x149ltce",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "x1ov1sdl",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x15r7cj3",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "x16me3o6",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "x1ud7p3u",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "xct3uda",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "x1ov1sdl",
      ":not([stylex-hack]) > * + *_marginBottom": "x149ltce",
      $$css: true,
    },
  },
  contentExternalSectionSpacingStyles: {
    bottom: { marginBottom: "x1yztbdb", $$css: true },
    top: { marginTop: "xw7yly9", $$css: true },
    end: {
      marginEnd: "xktsk01",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    start: {
      marginStart: "x1d52u69",
      marginLeft: null,
      marginRight: null,
      $$css: true,
    },
    horizontal: {
      marginStart: "x1d52u69",
      marginLeft: null,
      marginRight: null,
      marginEnd: "xktsk01",
      $$css: true,
    },
    vertical: {
      marginTop: "xw7yly9",
      marginBottom: "x1yztbdb",
      $$css: true,
    },
  },
  layoutContentExternalSectionSpacingStyles: {
    bottom: {
      ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
      $$css: true,
    },
    top: {
      ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
      $$css: true,
    },
    end: {
      ":not([stylex-hack]) > :not(:last-child)_marginEnd": "x1jjk293",
      ":not([stylex-hack]) > :not(:last-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:last-child)_marginRight": null,
      $$css: true,
    },
    start: {
      ":not([stylex-hack]) > :not(:first-child)_marginEnd": "xg3tqtt",
      ":not([stylex-hack]) > :not(:first-child)_marginLeft": null,
      ":not([stylex-hack]) > :not(:first-child)_marginRight": null,
      $$css: true,
    },
    horizontal: {
      ":not([stylex-hack]) > * + *_marginStart": "xe9zolg",
      ":not([stylex-hack]) > * + *_marginLeft": null,
      ":not([stylex-hack]) > * + *_marginRight": null,
      ":not([stylex-hack]) > * + *_marginEnd": "x1ywc1mj",
      $$css: true,
    },
    vertical: {
      ":not([stylex-hack]) > * + *_marginTop": "x1kxxb1g",
      ":not([stylex-hack]) > * + *_marginBottom": "x1jbr5dy",
      $$css: true,
    },
  },
};
