/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
const GeoPrivateDefaultAppearanceGeneratedStyles = (() => {
  const borderWidthStyles = {
    button: {
      borderTopWidth: "x972fbf",
      borderEndWidth: "xcfux6l",
      borderBottomWidth: "x1qhh985",
      borderStartWidth: "xm0m39n",
      $$css: true,
    },
    control: {
      borderTopWidth: "x972fbf",
      borderEndWidth: "xcfux6l",
      borderBottomWidth: "x1qhh985",
      borderStartWidth: "xm0m39n",
      $$css: true,
    },
    divider: {
      borderTopWidth: "x178xt8z",
      borderEndWidth: "xm81vs4",
      borderBottomWidth: "xso031l",
      borderStartWidth: "xy80clv",
      $$css: true,
    },
    frame: {
      borderTopWidth: "xamhcws",
      borderEndWidth: "xol2nv",
      borderBottomWidth: "xlxy82",
      borderStartWidth: "x19p7ews",
      $$css: true,
    },
    input: {
      borderTopWidth: "x178xt8z",
      borderEndWidth: "xm81vs4",
      borderBottomWidth: "xso031l",
      borderStartWidth: "xy80clv",
      $$css: true,
    },
    media: {
      borderTopWidth: "x178xt8z",
      borderEndWidth: "xm81vs4",
      borderBottomWidth: "xso031l",
      borderStartWidth: "xy80clv",
      $$css: true,
    },
  };

  const interactiveBorderWidthStyles = {
    button: { outlineWidth: "x1k57tk5", $$css: true },
    control: { outlineWidth: "x1k57tk5", $$css: true },
    divider: { outlineWidth: "x1qgsegg", $$css: true },
    frame: { outlineWidth: "x1de99jn", $$css: true },
    input: { outlineWidth: "x1qgsegg", $$css: true },
    media: { outlineWidth: "x1qgsegg", $$css: true },
  };

  const borderRadiusStyles = {
    addon: {
      borderTopStartRadius: "x1lcm9me",
      borderTopEndRadius: "x1yr5g0i",
      borderBottomEndRadius: "xrt01vj",
      borderBottomStartRadius: "x10y3i5r",
      $$css: true,
    },
    content: {
      borderTopStartRadius: "xhk9q7s",
      borderTopEndRadius: "x1otrzb0",
      borderBottomEndRadius: "x1i1ezom",
      borderBottomStartRadius: "x1o6z2jb",
      $$css: true,
    },
    container: {
      borderTopStartRadius: "x1lq5wgf",
      borderTopEndRadius: "xgqcy7u",
      borderBottomEndRadius: "x30kzoy",
      borderBottomStartRadius: "x9jhf4c",
      $$css: true,
    },
    control: {
      borderTopStartRadius: "xhk9q7s",
      borderTopEndRadius: "x1otrzb0",
      borderBottomEndRadius: "x1i1ezom",
      borderBottomStartRadius: "x1o6z2jb",
      $$css: true,
    },
    layer: {
      borderTopStartRadius: "x1lq5wgf",
      borderTopEndRadius: "xgqcy7u",
      borderBottomEndRadius: "x30kzoy",
      borderBottomStartRadius: "x9jhf4c",
      $$css: true,
    },
    rounded: {
      borderTopStartRadius: "xzolkzo",
      borderTopEndRadius: "x12go9s9",
      borderBottomEndRadius: "x1rnf11y",
      borderBottomStartRadius: "xprq8jg",
      $$css: true,
    },
  };

  const sizeStyles = {
    landscape16: { height: "xlup9mm", width: "xvy4d1p", $$css: true },
    landscape21: { height: "x158ke7r", width: "xq14iec", $$css: true },
    landscape24: { height: "xxk0z11", width: "x14qfxbe", $$css: true },
    landscape30: { height: "x1gnnpzl", width: "xzuapc8", $$css: true },
    landscape32: { height: "x10w6t97", width: "x1useyqa", $$css: true },
    landscape40: { height: "x1vqgdyp", width: "x1247r65", $$css: true },
    landscape41: { height: "x1njhlm6", width: "x1swbwvd", $$css: true },
    landscape48: { height: "xsdox4t", width: "xni59qk", $$css: true },
    landscape62: { height: "x1x0gksc", width: "x1vtj31x", $$css: true },
    landscape64: { height: "x1peatla", width: "x13oubkp", $$css: true },
    landscape80: { height: "xwzfr38", width: "xygnafs", $$css: true },
    landscape94: { height: "xyk13k4", width: "xzzq9k6", $$css: true },
    landscape96: { height: "xjp8j0k", width: "x1fznrkb", $$css: true },
    landscape118: { height: "x1xeopk8", width: "xgdcoeo", $$css: true },
    landscape144: { height: "x16d3s56", width: "x2qqsnf", $$css: true },
    landscape180: { height: "x1b51vyi", width: "xthkip5", $$css: true },
    landscape196: { height: "xzp6m1v", width: "x1i0n78g", $$css: true },
    landscape300: { height: "x1vd4hg5", width: "xbstwhj", $$css: true },
    portrait16: { height: "x1qx5ct2", width: "x1kky2od", $$css: true },
    portrait21: { height: "xd7y6wv", width: "x1kl0l3y", $$css: true },
    portrait24: { height: "x1gnnpzl", width: "xvy4d1p", $$css: true },
    portrait30: { height: "xrtz9ly", width: "x1849jeq", $$css: true },
    portrait32: { height: "x1vqgdyp", width: "x1td3qas", $$css: true },
    portrait40: { height: "x10wjd1d", width: "x100vrsf", $$css: true },
    portrait41: { height: "xaymia4", width: "x1r9kitl", $$css: true },
    portrait48: { height: "xng8ra", width: "x1useyqa", $$css: true },
    portrait62: { height: "x1kysglf", width: "xeepkih", $$css: true },
    portrait64: { height: "xwzfr38", width: "x1fu8urw", $$css: true },
    portrait80: { height: "xpyat2d", width: "x1dmp6jm", $$css: true },
    portrait94: { height: "x1najy0q", width: "x24u15m", $$css: true },
    portrait96: { height: "x1wkxgih", width: "x13oubkp", $$css: true },
    portrait118: { height: "x1xxjqy4", width: "x1sla5pk", $$css: true },
    portrait144: { height: "x1b51vyi", width: "x1fznrkb", $$css: true },
    portrait180: { height: "xtbh88u", width: "xzjbwwf", $$css: true },
    portrait196: { height: "x1n6b576", width: "x2i0jwv", $$css: true },
    portrait300: { height: "xijmrfd", width: "xdzyupr", $$css: true },
    portraitTall16: { height: "x1fgtraw", width: "x1kky2od", $$css: true },
    portraitTall21: { height: "xrtz9ly", width: "x1kl0l3y", $$css: true },
    portraitTall24: { height: "x5kalc8", width: "xvy4d1p", $$css: true },
    portraitTall30: { height: "x9dczf4", width: "x1849jeq", $$css: true },
    portraitTall32: { height: "xnnlda6", width: "x1td3qas", $$css: true },
    portraitTall40: { height: "x2x2exm", width: "x100vrsf", $$css: true },
    portraitTall41: { height: "xy75621", width: "x1r9kitl", $$css: true },
    portraitTall48: { height: "xcbkimw", width: "x1useyqa", $$css: true },
    portraitTall62: { height: "x41k7rp", width: "xeepkih", $$css: true },
    portraitTall64: { height: "x1ffmiix", width: "x1fu8urw", $$css: true },
    portraitTall80: { height: "x89wwaf", width: "x1dmp6jm", $$css: true },
    portraitTall94: { height: "x1yzmhis", width: "x24u15m", $$css: true },
    portraitTall96: { height: "x1a842fp", width: "x13oubkp", $$css: true },
    portraitTall118: { height: "x1mlwj4c", width: "x1sla5pk", $$css: true },
    portraitTall144: { height: "xrlp1an", width: "x1fznrkb", $$css: true },
    portraitTall180: { height: "xu3xrit", width: "xzjbwwf", $$css: true },
    portraitTall196: { height: "x1ad3yod", width: "x2i0jwv", $$css: true },
    portraitTall300: { height: "x1xy2ir9", width: "xdzyupr", $$css: true },
    square16: { height: "xlup9mm", width: "x1kky2od", $$css: true },
    square21: { height: "x158ke7r", width: "x1kl0l3y", $$css: true },
    square24: { height: "xxk0z11", width: "xvy4d1p", $$css: true },
    square30: { height: "x1gnnpzl", width: "x1849jeq", $$css: true },
    square32: { height: "x10w6t97", width: "x1td3qas", $$css: true },
    square40: { height: "x1vqgdyp", width: "x100vrsf", $$css: true },
    square41: { height: "x1njhlm6", width: "x1r9kitl", $$css: true },
    square48: { height: "xsdox4t", width: "x1useyqa", $$css: true },
    square62: { height: "x1x0gksc", width: "xeepkih", $$css: true },
    square64: { height: "x1peatla", width: "x1fu8urw", $$css: true },
    square80: { height: "xwzfr38", width: "x1dmp6jm", $$css: true },
    square94: { height: "xyk13k4", width: "x24u15m", $$css: true },
    square96: { height: "xjp8j0k", width: "x13oubkp", $$css: true },
    square118: { height: "x1xeopk8", width: "x1sla5pk", $$css: true },
    square144: { height: "x16d3s56", width: "x1fznrkb", $$css: true },
    square180: { height: "x1b51vyi", width: "xzjbwwf", $$css: true },
    square196: { height: "xzp6m1v", width: "x2i0jwv", $$css: true },
    square300: { height: "x1vd4hg5", width: "xdzyupr", $$css: true },
  };

  return {
    borderWidthStyles,
    interactiveBorderWidthStyles,
    borderRadiusStyles,
    sizeStyles,
  };
})();

export default GeoPrivateDefaultAppearanceGeneratedStyles;
