/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
export const ClickIDDomainBlacklistSVConfig = {
  domains: [
    "craigslist",
    "tfbnw.net",
    "flashtalking.com",
    "canadiantire.ca",
    "o2.co.uk",
    "archive.org",
    "reddit.com",
    "redd.it",
    "gmail.com",
    "cvk.gov.ua",
    "electoralsearch.in",
    "yahoo.com",
    "cve.mitre.org",
    "usenix.org",
    "ky.gov",
    "voteohio.gov",
    "vote.pa.gov",
    "oversightboard.com",
    "wi.gov",
    "pbs.twimg.com",
    "media.discordapp.net",
    "vastadeal.com",
    "theaustralian.com.au",
    "alloygator.com",
    "elsmannimmobilien.de",
    "news.com.au",
    "dennisbonnen.com",
    "stoett.com",
    "investorhour.com",
    "perspectivasur.com",
    "bonnegueule.fr",
    "firstent.org",
    "twitpic.com",
    "kollosche.com.au",
    "nau.edu",
    "arcourts.gov",
    "lomberg.de",
    "network4.hu",
    "balloonrace.com",
    "awstrack.me",
    "ic3.gov",
    "sos.wyo.gov",
    "cnpq.br",
    "0.discoverapp.com",
    "apple.com",
    "apple.co",
    "applecard.apple",
    "services.apple",
    "appletvplus.com",
    "applepay.apple",
    "wallet.apple",
    "beatsbydre.com",
    "dinn.com.mx",
    "soriana.com",
    "facebook.sso.datasite.com",
    "fycextras.com",
    "rik.parlament.gov.rs",
    "dge.sn",
  ],
};
