/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
export const IntlCompactDecimalNumberFormatConfig = {
  short_patterns: {
    3: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
    },
    4: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
    },
    5: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "K",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "K",
      },
    },
    6: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
    },
    7: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
    },
    8: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "M",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "M",
      },
    },
    9: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
    },
    10: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
    },
    11: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "B",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "B",
      },
    },
    12: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
    },
    13: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
    },
    14: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: "T",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: "T",
      },
    },
  },
  long_patterns: {
    3: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
    },
    4: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
    },
    5: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " thousand",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " thousand",
      },
    },
    6: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
    },
    7: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
    },
    8: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " million",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " million",
      },
    },
    9: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
    },
    10: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
    },
    11: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " billion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " billion",
      },
    },
    12: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 1,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
    },
    13: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 2,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
    },
    14: {
      4: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
      24: {
        min_fraction_digits: null,
        min_integer_digits: 3,
        positive_prefix_pattern: "",
        positive_suffix_pattern: " trillion",
        negative_prefix_pattern: "-",
        negative_suffix_pattern: " trillion",
      },
    },
  },
};
