// __d(
//   "BusinessAssetTypesUppercase$FbtEnum",
//   [],
//   function (a, b, c, d, e, f) {
//     "use strict";
//     a = {
//       "ad-account": "Ad Account",
//       "ad-study": "Lift Study",
//       app: "App",
//       "block-list": "Block List",
//       "white-list": "Publisher Allow List",
//       brand: "Business",
//       "business-unit": "Line of Business",
//       "catalog-segment": "Catalog Segment",
//       "creator-seller-profile": "Shop",
//       "custom-conversion": "Custom Conversion",
//       "event-source-group": "Event Source Group",
//       "example-cat": "Cat (do not translate)",
//       "owned-domain": "Domain",
//       "news-page": "News Page",
//       "instagram-account-v2": "Instagram Account",
//       "leads-access": "Leads Access",
//       "monetization-property": "Property",
//       "offline-event-set": "Offline Event Set",
//       "events-dataset": "Dataset",
//       "business-locations-wrapper": "Page Structure",
//       page: "Page",
//       "profile-plus": "Profile",
//       "payout-method": "Payment Account",
//       pixel: "Pixel",
//       "product-catalog": "Catalog",
//       "registered-trademark": "Registered Trademark",
//       "shared-audience": "Shared Audience",
//       "sliced-event-source-group": "Sliced Event Source Group",
//       user: "Person",
//       "whatsapp-business-account": "WhatsApp Account",
//       "business-resource-group": "Business Asset Group",
//       "business-creative-folder": "Business Creative Folder",
//       "dynamic-content-set": "Content Allow List",
//       "ads-event-source": "Ads Event Source",
//       "seller-profile": "Commerce Account",
//       "legal-entity": "Legal Entity",
//       "advanced-analytics-instance": "Instance",
//       "events-dataset-new": "Dataset",
//       "offsite-email-account": "Email Account",
//       "creator-marketplace-brand-profile": "Creator Marketplace Account",
//       "mv4b-billable-account": "Meta Verified Account",
//     };
//     e.exports = a;
//   },
//   null
// );

const BusinessAssetTypesUppercaseFbtEnum = {
  "ad-account": "Ad Account",
  "ad-study": "Lift Study",
  app: "App",
  "block-list": "Block List",
  "white-list": "Publisher Allow List",
  brand: "Business",
  "business-unit": "Line of Business",
  "catalog-segment": "Catalog Segment",
  "creator-seller-profile": "Shop",
  "custom-conversion": "Custom Conversion",
  "event-source-group": "Event Source Group",
  "example-cat": "Cat (do not translate)",
  "owned-domain": "Domain",
  "news-page": "News Page",
  "instagram-account-v2": "Instagram Account",
  "leads-access": "Leads Access",
  "monetization-property": "Property",
  "offline-event-set": "Offline Event Set",
  "events-dataset": "Dataset",
  "business-locations-wrapper": "Page Structure",
  page: "Page",
  "profile-plus": "Profile",
  "payout-method": "Payment Account",
  pixel: "Pixel",
  "product-catalog": "Catalog",
  "registered-trademark": "Registered Trademark",
  "shared-audience": "Shared Audience",
  "sliced-event-source-group": "Sliced Event Source Group",
  user: "Person",
  "whatsapp-business-account": "WhatsApp Account",
  "business-resource-group": "Business Asset Group",
  "business-creative-folder": "Business Creative Folder",
  "dynamic-content-set": "Content Allow List",
  "ads-event-source": "Ads Event Source",
  "seller-profile": "Commerce Account",
  "legal-entity": "Legal Entity",
  "advanced-analytics-instance": "Instance",
  "events-dataset-new": "Dataset",
  "offsite-email-account": "Email Account",
  "creator-marketplace-brand-profile": "Creator Marketplace Account",
  "mv4b-billable-account": "Meta Verified Account",
} as const;

export default BusinessAssetTypesUppercaseFbtEnum;
