/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */

const MAWLocalizationType = {
  EMPTY_SNIPPET: "emptySnippet",
  CURRENT_USER_CREATED_GROUP: "currentUserCreatedGroup",
  PARTICIPANT_CREATED_GROUP: "participantCreatedGroup",
  UNKNOWN_USER_CREATED_GROUP: "unknownUserCreatedGroup",
  CURRENT_USER_NAMED_GROUP: "currentUserNamedGroup",
  UNKNOWN_USER_NAMED_GROUP: "unknownUserNamedGroup",
  PARTICIPANT_NAMED_GROUP: "participantNamedGroup",
  CURRENT_USER_ADDED_DEVICE: "currentUserAddedDevice",
  PARTICIPANT_ADDED_DEVICE: "participantAddedDevice",
  CURRENT_USER_REMOVED_DEVICE: "currentUserRemovedDevice",
  PARTICIPANT_REMOVED_DEVICE: "participantRemovedDevice",
  CURRENT_USER_UPDATED_DEVICE: "currentUserUpdatedDevice",
  PARTICIPANT_UPDATED_DEVICE: "participantUpdatedDevice",
  CURRENT_USER_ADDED_ONE_PARTICIPANT: "currentUserAddedOneParticipant",
  CURRENT_USER_ADDED_TWO_PARTICIPANTS: "currentUserAddedTwoParticipant",
  CURRENT_USER_ADDED_MORE_THAN_TWO_PARTICIPANTS:
    "currentUserAddedMoreThanTwoParticipant",
  PARTICIPANT_ADDED_YOU: "participantAddedYou",
  PARTICIPANT_ADDED_YOU_AND_ONE_USER: "participantAddedYouAndOneUser",
  PARTICIPANT_ADDED_YOU_AND_MORE_THAN_ONE_USERS:
    "participantAddedYouAndMoreThanOneUsers",
  UNKNOWN_USER_ADDED_YOU: "unknownUserAddedYou",
  UNKNOWN_USER_ADDED_YOU_AND_ONE_USER: "unknownUserAddedYouAndOneUser",
  UNKNOWN_USER_ADDED_YOU_AND_MORE_THAN_ONE_USER:
    "unknownUserAddedYouAndMoreThanOneUser",
  UNKNOWN_USER_ADDED_ONE_USER: "unknownUserAddedOneUser",
  UNKNOWN_USER_ADDED_TWO_USER: "unknownUserAddedTwoUser",
  UNKNOWN_USER_ADDED_MORE_THAN_TWO_USER: "unknownUserAddedMoreThanTwoUser",
  PARTICIPANT_ADDED_ONE_USER: "participantAddedOneUser",
  PARTICIPANT_ADDED_TWO_USER: "participantAddedTwoUser",
  PARTICIPANT_ADDED_MORE_THAN_TWO_USER: "participantAddedMoreThanTwoUser",
  CURRENT_USER_REMOVED_ONE_PARTICIPANT: "currentUserRemovedOneParticipant",
  CURRENT_USER_REMOVED_TWO_PARTICIPANTS: "currentUserRemovedTwoParticipant",
  CURRENT_USER_REMOVED_MORE_THAN_TWO_PARTICIPANTS:
    "currentUserRemovedMoreThanTwoParticipant",
  PARTICIPANT_REMOVED_YOU: "participantRemovedYou",
  PARTICIPANT_REMOVED_YOU_AND_ONE_USER: "participantRemovedYouAndOneUser",
  PARTICIPANT_REMOVED_YOU_AND_MORE_THAN_ONE_USERS:
    "participantRemovedYouAndMoreThanOneUsers",
  UNKNOWN_USER_REMOVED_YOU: "unknownUserRemovedYou",
  UNKNOWN_USER_REMOVED_YOU_AND_ONE_USER: "unknownUserRemovedYouAndOneUser",
  UNKNOWN_USER_REMOVED_YOU_AND_MORE_THAN_ONE_USER:
    "unknownUserRemovedYouAndMoreThanOneUser",
  UNKNOWN_USER_REMOVED_ONE_USER: "unknownUserRemovedOneUser",
  UNKNOWN_USER_REMOVED_TWO_USER: "unknownUserRemovedTwoUser",
  UNKNOWN_USER_REMOVED_MORE_THAN_TWO_USER: "unknownUserRemovedMoreThanTwoUser",
  PARTICIPANT_REMOVED_ONE_USER: "participantRemovedOneUser",
  PARTICIPANT_REMOVED_TWO_USER: "participantRemovedTwoUser",
  PARTICIPANT_REMOVED_MORE_THAN_TWO_USER: "participantRemovedMoreThanTwoUser",
  PARTICIPANT_LEFT_GROUP: "participantLeftGroup",
  CURRENT_USER_LEFT_GROUP: "currentUserLeftGroup",
  CURRENT_USER_GOT_PROMOTED: "currentUserGotPromoted",
  CURRENT_USER_GOT_DEMOTED: "currentUserGotDemoted",
  PARTICIPANT_GOT_PROMOTED: "participantGotPromoted",
  PARTICIPANT_GOT_DEMOTED: "participantGotDemoted",
  PARTICIPANT_PROMOTED_YOU: "participantPromotedYou",
  PARTICIPANT_DEMOTED_YOU: "participantDemotedYou",
  CURRENT_USER_PROMOTED_PARTICIPANT: "currentUserPromotedParticipant",
  CURRENT_USER_DEMOTED_PARTICIPANT: "currentUserDemotedParticipant",
  PARTICIPANT_DEMOTED_PARTICIPANT: "participantDemotedParticipant",
  PARTICIPANT_PROMOTED_PARTICIPANT: "participantPromotedParticipant",
  PARTICIPANT_SELF_DEMOTED: "participantSelfDemoted",
  CURRENT_USER_SELF_DEMOTED: "currentUserSelfDemoted",
  CURRENT_USER_SEND_TEXT: "currentUserSendText",
  CURRENT_USER_SEND_IMAGE: "currentUserSendImage",
  CURRENT_USER_SEND_VIDEO: "currentUserSendVideo",
  CURRENT_USER_SEND_AUDIO: "currentUserSendAudio",
  CURRENT_USER_SEND_GIF: "currentUserSendGif",
  CURRENT_USER_SEND_STICKER: "currentUserSendSticker",
  PARTICIPANT_SEND_TEXT: "participantSendText",
  PARTICIPANT_SEND_TEXT_IN_GROUP: "participantSendTextInGroup",
  PARTICIPANT_SEND_IMAGE: "participantSendImage",
  PARTICIPANT_SEND_VIDEO: "participantSendVideo",
  PARTICIPANT_SEND_AUDIO: "participantSendAudio",
  PARTICIPANT_SEND_GIF: "participantSendGif",
  PARTICIPANT_SEND_STICKER: "participantSendSticker",
  UNAVAILABLE_SNIPPET: "unavailableSnippet",
  TWO_USERS_CONNECTED: "twoUsersConnected",
  TWO_USERS_CONNECTED_ONE_MSPLIT: "twoUsersConnectedOneMSplit",
  REACHABILITY_ERROR: "reachabilityError",
  UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_SECONDS:
    "unknownUserEphemeralSettingTurnedOnSeconds",
  UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_MINUTES:
    "unknownUserEphemeralSettingTurnedOnMinutes",
  UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_HOURS:
    "unknownUserEphemeralSettingTurnedOnHours",
  UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_ON_DAYS:
    "unknownUserEphemeralSettingTurnedOnDays",
  YOU_EPHEMERAL_SETTING_TURNED_ON_SECONDS: "youEphemeralSettingTurnedOnSeconds",
  YOU_EPHEMERAL_SETTING_TURNED_ON_MINUTES: "youEphemeralSettingTurnedOnMinutes",
  YOU_EPHEMERAL_SETTING_TURNED_ON_HOURS: "youEphemeralSettingTurnedOnHours",
  YOU_EPHEMERAL_SETTING_TURNED_ON_DAYS: "youEphemeralSettingTurnedOnDays",
  PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_SECONDS:
    "participantEphemeralSettingTurnedOnSeconds",
  PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_MINUTES:
    "participantEphemeralSettingTurnedOnMinutes",
  PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_HOURS:
    "participantEphemeralSettingTurnedOnHours",
  PARTICIPANT_EPHEMERAL_SETTING_TURNED_ON_DAYS:
    "participantEphemeralSettingTurnedOnDays",
  UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_SECONDS:
    "unknownUserEphemeralSettingChangeSeconds",
  UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_MINUTES:
    "unknownUserEphemeralSettingChangeMinutes",
  UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_HOURS:
    "unknownUserEphemeralSettingChangeHours",
  UNKNOWN_USER_EPHEMERAL_SETTING_CHANGE_DAYS:
    "unknownUserEphemeralSettingChangeDays",
  YOU_EPHEMERAL_SETTING_CHANGE_SECONDS: "youEphemeralSettingChangeSeconds",
  YOU_EPHEMERAL_SETTING_CHANGE_MINUTES: "youEphemeralSettingChangeMinutes",
  YOU_EPHEMERAL_SETTING_CHANGE_HOURS: "youEphemeralSettingChangeHours",
  YOU_EPHEMERAL_SETTING_CHANGE_DAYS: "youEphemeralSettingChangeDays",
  PARTICIPANT_EPHEMERAL_SETTING_CHANGE_SECONDS:
    "participantEphemeralSettingChangeSeconds",
  PARTICIPANT_EPHEMERAL_SETTING_CHANGE_MINUTES:
    "participantEphemeralSettingChangeMinutes",
  PARTICIPANT_EPHEMERAL_SETTING_CHANGE_HOURS:
    "participantEphemeralSettingChangeHours",
  PARTICIPANT_EPHEMERAL_SETTING_CHANGE_DAYS:
    "participantEphemeralSettingChangeDays",
  UNKNOWN_USER_EPHEMERAL_SETTING_TURNED_OFF:
    "unknownUserEphemeralSettingTurnedOff",
  YOU_EPHEMERAL_SETTING_TURNED_OFF: "youEphemeralSettingTurnedOff",
  PARTICIPANT_EPHEMERAL_SETTING_TURNED_OFF:
    "participantEphemeralSettingTurnedOff",
  EPHEMERAL_SETTINGS_AUTO_RESET: "ephemeralSettingsAutoReset",
  CURRENT_USER_UNSENT_MESSAGE: "currentUserUnsentMessage",
  PARTICIPANT_UNSENT_MESSAGE: "participantUnsentMessage",
  PARTICIPANT_REACT_MESSAGE: "participantReactMessage",
  PARTICIPANT_REACT_MESSAGE_IN_GROUP: "participantReactMessageInGroup",
  UNKNOWN_USER_EPHEMERAL_TAKE_SCREENSHOT: "unknownUserEphemeralTakeScreenshot",
  UNKNOWN_USER_EPHEMERAL_RECORD_SCREEN: "unknownUserEphemeralRecordScreen",
  YOU_EPHEMERAL_TAKE_SCREENSHOT: "youEphemeralTakeScreenshot",
  YOU_EPHEMERAL_RECORD_SCREEN: "youEphemeralRecordScreen",
  PARTICIPANT_EPHEMERAL_TAKE_SCREENSHOT: "participantEphemeralTakeScreenshot",
  PARTICIPANT_EPHEMERAL_RECORD_SCREEN: "participantEphemeralRecordScreen",
  ICDC_ALERT_ADMIN_MESSAGE: "icdcAlertAdminMessage",
  YOUR_DEVICE_ICDC_ALERT_ADMIN_MESSAGE: "yourDeviceICDCAlertAdminMessage",
  CUTOVER_THREAD_ADMIN_MESSAGE: "cutoverThreadAdminMessage",
  CUTOVER_IGD_THREAD_ADMIN_MESSAGE: "cutoverIGDThreadAdminMessage",
  CUTOVER_ROLLBACK_ADMIN_MESSAGE: "cutoverRollbackAdminMessage",
  CURRENT_USER_SEND_ATTACHMENT: "currentUserSendAttachment",
  PARTICIPANT_SEND_ATTACHMENT: "participantSendAttachment",
  CURRENT_USER_SENT_POST: "currentUserSentPost",
  CURRENT_USER_SENT_REEL: "currentUserSentReel",
  CURRENT_USER_SENT_STORY: "currentUserSentStory",
  CURRENT_USER_SENT_EVENT: "currentUserSentEvent",
  CURRENT_USER_MENTIONED_STORY_IG: "currentUserMentionedStoryIG",
  CURRENT_USER_RECEIVED_STORY_MENTION_IG: "currentUserReceivedStoryMentionIG",
  PARTICIPANT_SENT_POST: "participantSentPost",
  PARTICIPANT_SENT_REEL: "participantSentReel",
  PARTICIPANT_SENT_STORY: "participantSentStory",
  PARTICIPANT_SENT_EVENT: "participantSentEvent",
  CURRENT_USER_SENT_STORY_HIGHLIGHT: "currentUserSentStoryHighlight",
  PARTICIPANT_SENT_STORY_HIGHLIGHT: "participantSentStoryHighlight",
  DUAL_THREAD_CUTOVER_ADMIN_MESSAGE: "dualThreadCutoverAdminMessage",
  E2EE_THREAD_DESCRIPTION: "e2eeThreadDescription",
  DEBUG_MSG: "debugMsg",
  CURRENT_USER_MISSED_AUDIO_CALL: "currentUserMissedAudioCall",
  PARTICIPANT_MISSED_AUDIO_CALL: "participantMissedAudioCall",
  CURRENT_USER_MISSED_VIDEO_CALL: "currentUserMissedVideoCall",
  PARTICIPANT_MISSED_VIDEO_CALL: "participantMissedVideoCall",
  CURRENT_USER_AUDIO_CALLED: "currentUserAudioCalled",
  PARTICIPANT_AUDIO_CALLED: "participantAudioCalled",
  CURRENT_USER_VIDEO_CALLED: "currentUserVideoCalled",
  PARTICIPANT_VIDEO_CALLED: "participantVideoCalled",
  CURRENT_USER_STARTED_GROUP_AUDIO_CALL: "currentUserStartedGroupAudioCall",
  PARTICIPANT_STARTED_GROUP_AUDIO_CALL: "participantStartedGroupAudioCall",
  CURRENT_USER_STARTED_GROUP_VIDEO_CALL: "currentUserStartedGroupVideoCall",
  PARTICIPANT_STARTED_GROUP_VIDEO_CALL: "participantStartedGroupVideoCall",
  CURRENT_USER_CUSTOMIZE_HOTLIKE: "currentUserCustomizeHotlike",
  PARTICIPANT_CUSTOMIZE_HOTLIKE: "participantCustomizeHotlike",
  CURRENT_USER_CUSTOMIZE_NICKNAME: "currentUserCustomizeNickname",
  CURRENT_USER_CUSTOMIZE_THEME: "currentUserCustomizeTheme",
  CURRENT_USER_CUSTOMIZE_PHOTO: "currentUserCustomizePhoto",
  CURRENT_USER_PINNED_MESSAGE: "currentUserPinnedMessage",
  CURRENT_USER_UNPINNED_MESSAGE: "currentUserUnpinnedMessage",
  PARTICIPANT_CUSTOMIZE_PARTICIPANT_NICKNAME:
    "participantCustomizeParticipantNickname",
  PARTICIPANT_CLEAR_PARTICIPANT_NICKNAME: "participantClearParticipantNickname",
  PARTICIPANT_CUSTOMIZE_THEME: "participantCustomizeTheme",
  PARTICIPANT_CUSTOMIZE_PHOTO: "participantCustomizePhoto",
  PARTICIPANT_CUSTOMIZE_CURRENT_USER_NICKNAME:
    "participantCustomizeCurrentUserNickname",
  PARTICIPANT_PINNED_MESSAGE: "participantPinnedMessage",
  PARTICIPANT_UNPINNED_MESSAGE: "participantUnpinnedMessage",
  CURRENT_USER_SET_OWN_NICKNAME: "currentUserSetOwnNickname",
  CURRENT_USER_CLEAR_OWN_NICKNAME: "currentUserClearOwnNickname",
  CURRENT_USER_CLEAR_PARTICIPANT_NICKNAME:
    "currentUserClearParticipantNickname",
  PARTICIPANT_SET_OWN_NICKNAME: "participantSetOwnNickname",
  PARTICIPANT_CLEAR_OWN_NICKNAME: "participantClearOwnNickname",
  PARTICIPANT_CLEAR_CURRENT_USER_NICKNAME:
    "participantClearCurrentUserNickname",
  CURRENT_USER_SET_ADD_MODE_ADMIN_ONLY: "currentUserSetAddModeAdminOnly",
  CURRENT_USER_SET_ADD_MODE_ALL_MEMBERS: "currentUserSetAddModeAllMembers",
  PARTICIPANT_SET_ADD_MODE_ADMIN_ONLY: "participantSetAddModeAdminOnly",
  PARTICIPANT_SET_ADD_MODE_ALL_MEMBERS: "participantSetAddModeAllMembers",
  SERVER_SET_ADD_MODE_ADMIN_ONLY: "serverSetAddModeAdminOnly",
  SERVER_SET_ADD_MODE_ALL_MEMBERS: "serverSetAddModeAllMembers",
  CURRENT_USER_BUMPED_OWN_MESSAGE: "currentUserBumpedOwnMessage",
  CURRENT_USER_BUMPED_MESSAGE: "currentUserBumpedMessage",
  PARTICIPANT_BUMPED_OWN_MESSAGE: "participantBumpedOwnMessage",
  PARTICIPANT_BUMPED_PARTICIPANT_MESSAGE: "participantBumpedParticipantMessage",
  PARTICIPANT_BUMPED_CURRENT_USER_MESSAGE:
    "participantBumpedCurrentUserMessage",
  USER_SEND_UNAVAILABLE_MESSAGE: "userSendUnavailableMessage",
  USER_SEND_ENCRYPTED_MESSAGE: "userSendEncryptedMessage",
  CURRENT_USER_SEND_UNRENDERABLE_MESSAGE: "currentUserSendUnrenderableMessage",
  PARTICIPANT_SEND_UNRENDERABLE_MESSAGE: "participantSendUnrenderableMessage",
  CURRENT_USER_SEND_LOCATION: "currentUserSendLocation",
  PARTICIPANT_SEND_LOCATION: "participantSendLocation",
  CURRENT_USER_SEND_POLL_CREATION: "currentUserSendPollCreation",
  PARTICIPANT_SEND_POLL_CREATION: "participantSendPollCreation",
  CURRENT_USER_SEND_CONTACT_SHARE: "currentUserSendContactShare",
  PARTICIPANT_SEND_CONTACT_SHARE: "participantSendContactShare",
  CURRENT_USER_SEND_STORY_MENTION: "currentUserSendStoryMention",
  PARTICIPANT_SEND_STORY_MENTION: "participantSendStoryMention",
  META_AI_SEND_MESSAGE: "metaAISendMessage",
  CURRENT_USER_SEND_BUMP_MESSAGE: "currentUserSendBumpMessage",
  PARTICIPANT_SEND_BUMP_MESSAGE: "participantSendBumpMessage",
  PARTICIPANT_SEND_BUMP_MESSAGE_ORIGINAL_UNAVAILABLE:
    "participantSendBumpMessageOriginalUnavailable",
  CURRENT_USER_SEND_STICKER_RECEIVER_FETCH_MESSAGE:
    "currentUserSendStickerReceiverFetchMessage",
  PARTICIPANT_SEND_STICKER_RECEIVER_FETCH_MESSAGE:
    "participantSendStickerReceiverFetchMessage",
};

export default MAWLocalizationType;
