/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
const MessagingThreadType = Object.freeze({
  COMMUNITY_FOLDER: 17,
  COMMUNITY_GROUP: 18,
  COMMUNITY_GROUP_UNJOINED: 19,
  COMMUNITY_CHANNEL_CATEGORY: 20,
  COMMUNITY_PRIVATE_HIDDEN_JOINED_THREAD: 21,
  COMMUNITY_PRIVATE_HIDDEN_UNJOINED_THREAD: 22,
  COMMUNITY_BROADCAST_JOINED_THREAD: 23,
  COMMUNITY_BROADCAST_UNJOINED_THREAD: 24,
  COMMUNITY_GROUP_INVITED_UNJOINED: 25,
  COMMUNITY_SUB_THREAD: 26,
  DISCOVERABLE_PUBLIC_CHAT: 150,
  DISCOVERABLE_PUBLIC_CHAT_UNJOINED: 151,
  DISCOVERABLE_PUBLIC_BROADCAST_CHAT: 152,
  DISCOVERABLE_PUBLIC_BROADCAST_CHAT_UNJOINED: 153,
  DISCOVERABLE_PUBLIC_CHAT_V2: 154,
  DISCOVERABLE_PUBLIC_CHAT_V2_UNJOINED: 155,
  ONE_TO_ONE: 1,
  GROUP: 2,
  ROOM: 3,
  MONTAGE: 4,
  MARKETPLACE: 5,
  FOLDER: 6,
  TINCAN_ONE_TO_ONE: 7,
  TINCAN_GROUP_DISAPPEARING: 8,
  CARRIER_MESSAGING_ONE_TO_ONE: 10,
  CARRIER_MESSAGING_GROUP: 11,
  TINCAN_ONE_TO_ONE_DISAPPEARING: 13,
  PAGE_FOLLOW_UP: 14,
  SECURE_MESSAGE_OVER_WA_ONE_TO_ONE: 15,
  SECURE_MESSAGE_OVER_WA_GROUP: 16,
  PINNED: 101,
  LWG: 102,
  XAC_GROUP: 200,
  AI_BOT: 201,
});

export default MessagingThreadType;
