/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
const DEFAULT_MAX_REACTION_PREVIEWED_ALLOWED = 3;
const CM_MAX_REACTION_EMOJIS_ALLOWED = 20;
const PUBLIC_CHANNELS_MAX_REACTIONS_EMOJIS_PREVIEWED_WHEN_COLLAPSED = 3;
const SPACING_PER_COUNT_CHARACTER = 9;
const REACTIONS_ROW_EXPAND_COLLAPSE_ANIMATION_TOTAL_DURATION = 180;
const REACTION_BUTTON_BUBBLE_EASE_FACTOR = 2;

export {
  CM_MAX_REACTION_EMOJIS_ALLOWED,
  DEFAULT_MAX_REACTION_PREVIEWED_ALLOWED,
  PUBLIC_CHANNELS_MAX_REACTIONS_EMOJIS_PREVIEWED_WHEN_COLLAPSED,
  REACTION_BUTTON_BUBBLE_EASE_FACTOR,
  REACTIONS_ROW_EXPAND_COLLAPSE_ANIMATION_TOTAL_DURATION,
  SPACING_PER_COUNT_CHARACTER,
};
