/**
 * @fileoverview
 * Copyright (c) Xuan Tien and affiliated entities.
 * All rights reserved. This source code is licensed under the MIT license.
 * See the LICENSE file in the root directory for details.
 */
const MWPAudioPlayerSharedStyles = {
  bar: {
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "x1inr27j",
    borderTopEndRadius: "x1vcqv9c",
    borderBottomEndRadius: "xfrm7hi",
    borderBottomStartRadius: "xpbad92",
    boxShadow: "x49dmcg",
    height: "xn3w4p2",
    position: "x10l6tqk",
    top: "xwa60dl",
    transform: "x1cb1t30",
    width: "x51ohtg",
    zIndex: "x1vjfegm",
    ,
  },
  common: {
    alignItems: "x6s0dn4",
    alignSelf: "xkh2ocl",
    backgroundAttachment: "x1nr1p0w",
    borderTopStartRadius: "x1tlxs6b",
    borderTopEndRadius: "x1g8br2z",
    borderBottomEndRadius: "x1gn5b1j",
    borderBottomStartRadius: "x230xth",
    display: "x78zum5",
    flexGrow: "x1iyjqo2",
    justifyContent: "x1qughib",
    outline: "x1k4qllp",
    ,
  },
  commonIncoming: {
    backgroundColor: "x1xr0vuk",
    ,
  },
  commonOutgoing: {
    backgroundColor: "x11jlvup",
    ,
  },
  commonOutgoingReply: {
    backgroundImage: "xl54vp5",
    ,
  },
  commonReply: {
    outline: "x1ucz5p",
    ,
  },
  container: {
    alignItems: "x6s0dn4",
    display: "x78zum5",
    flexGrow: "x1iyjqo2",
    justifyContent: "x1qughib",
    overflowX: "x6ikm8r",
    overflowY: "x10wlt62",
    position: "relative",
    ,
  },
  highlight: {
    height: "x5yr21d",
    position: "x10l6tqk",
    start: "x17qophe",
    left: null,
    right: null,
    top: "x13vifvy",
    width: "xh8yej3",
    ,
  },
  incomingWaveFormStyle: {
    fill: "x1f9y4dh",
    ,
  },
  mask: {
    height: "x5yr21d",
    position: "x10l6tqk",
    width: "xh8yej3",
    ,
  },
  outgoingWaveFormStyle: {
    fill: "xe3v8dz",
    ,
  },
  playbackButtonContainer: {
    marginStart: "x1mnrxsn",
    marginLeft: null,
    marginRight: null,
    marginEnd: "x1w0mnb",
    ,
  },
  pressable: {
    alignItems: "x6s0dn4",
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "x14yjl9h",
    borderTopEndRadius: "xudhj91",
    borderBottomEndRadius: "x18nykt9",
    borderBottomStartRadius: "xww2gxu",
    display: "x78zum5",
    height: "xxk0z11",
    justifyContent: "xl56j7k",
    minWidth: "xnei2rj",
    ,
  },
  rightSideBottom: {
    backgroundColor: "x14hiurz",
    borderTopStartRadius: "xfj52jq",
    borderTopEndRadius: "xykzs3s",
    borderBottomEndRadius: "x17xv1ja",
    borderBottomStartRadius: "x1mvicbb",
    ,
  },
  rightSideImprove: {
    marginStart: "x16n37ib",
    marginLeft: null,
    marginRight: null,
    marginEnd: "xq8finb",
    width: "x1691je0",
    ,
  },
  rightSideMargin: {
    marginTop: "x1gslohp",
    ,
  },
  rightSideTop: {
    alignItems: "x6s0dn4",
    color: "x1a3ma36",
    display: "x78zum5",
    fontSize: "x1nxh6w3",
    fontWeight: "x1s688f",
    height: "xi0exxh",
    justifyContent: "xl56j7k",
    marginStart: "x1mnrxsn",
    marginLeft: null,
    marginRight: null,
    marginEnd: "x1w0mnb",
    position: "relative",
    userSelect: "x87ps6o",
    width: "x1r9kitl",
    ,
  },
  scrubber: {
    alignItems: "x6s0dn4",
    display: "x78zum5",
    height: "x5yr21d",
    position: "relative",
    width: "xh8yej3",
    zIndex: "x1vjfegm",
    ,
  },
  transparent: {
    height: "x5yr21d",
    overflowX: "x6ikm8r",
    overflowY: "x10wlt62",
    paddingTop: 0,
    paddingEnd: 0,
    paddingBottom: 0,
    paddingStart: 0,
    position: "relative",
    "::after_borderTopColor": "x14617ij",
    "::after_borderEndColor": "x1b5s2of",
    "::after_borderBottomColor": "xv84cap",
    "::after_borderStartColor": "x15ngzmr",
    "::after_borderTopStartRadius": "xwuuf8d",
    "::after_borderTopEndRadius": "xpd6q6o",
    "::after_borderBottomEndRadius": "x1n6g0fn",
    "::after_borderBottomStartRadius": "xu4xob7",
    "::after_borderTopStyle": "xynf4tj",
    "::after_borderEndStyle": "xdspwft",
    "::after_borderBottomStyle": "x1r9ni5o",
    "::after_borderStartStyle": "x1d52zm6",
    "::after_borderTopWidth": "x1gnji40",
    "::after_borderEndWidth": "xymhjbi",
    "::after_borderBottomWidth": "x1ekxc0f",
    "::after_borderStartWidth": "x5arhyh",
    "::after_bottom": "x14apmda",
    "::after_content": "",
    "::after_display": "xhkezso",
    "::after_end": "xhyvd7x",
    "::after_left": null,
    "::after_right": null,
    "::after_pointerEvents": "x2q1x1w",
    "::after_position": "x1j6awrg",
    "::after_start": "x1aneyt",
    "::after_top": "xso615a",
    ,
  },
  transparentBar: {
    backgroundColor: "xjbqb8w",
    borderTopStartRadius: "x1inr27j",
    borderTopEndRadius: "x1vcqv9c",
    borderBottomEndRadius: "xfrm7hi",
    borderBottomStartRadius: "xpbad92",
    boxShadow: "x49dmcg",
    height: "xn3w4p2",
    position: "x10l6tqk",
    top: "xwa60dl",
    transform: "x1cb1t30",
    width: "x51ohtg",
    zIndex: "x1vjfegm",
    ,
  },
  waveform: {
    height: "xn3w4p2",
    position: "relative",
    width: "xh8yej3",
    ,
  },
};

export default MWPAudioPlayerSharedStyles;
